# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CESQCPlugin
                                 A QGIS plugin
 QC tool for disconnected poles and chambers within a selected polygon
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-12-30
        copyright            : (C) 2025 by Skiddelzzz
        email                : zziehl@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


from .ces_qc_hld_plugin import CESQCPlugin

def classFactory(iface):
    return CESQCPlugin(iface)
